# Site settings
title: "Những Người Mẹ"
url-title: "Những Người Mẹ"
description: "Những Người Mẹ và nơi hẹn hò"
paginate: 100
url: "https://itechsoftware24h.com/"
permalink: /:year/:month/:title/
future: false
defaults:
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
      excerpt_words: 25

# Build settings
markdown: kramdown
highlighter: rouge
kramdown:
  input: GFM
  syntax_highlighter: rouge
sass:
  sass_dir: _sass
  style: compressed
  deploy_style: compressed

gems: [jekyll-paginate]
